declare const body: HTMLBodyElement;
declare const timeline: any;
declare const to: any;
declare const width: 80;
declare const height: 80;
declare let renderer: any;
declare const scene: any;
declare const camera: any;
declare function rectangle(ctx: any, x: any, y: any, width: any, height: any, radius: any): void;
declare function rectangleReverse(ctx: any, x: any, y: any, width: any, height: any, radius: any): void;
declare let rect: any;
declare var rectSmall: any;
declare let shape: any;
declare const geometry: any;
declare let material: any;
declare let donut: any;
declare let planeGeometry: any;
declare let planeMaterial: any;
declare const plane: any;
declare const lightFront: any;
declare const d: 200;
declare const lightTop: any;
declare var rotate: any;
declare function render(): void;
